# Generated by Django 3.1.4 on 2020-12-07 13:07

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chusen', '0002_auto_20201207_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='作成日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='ended_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='締め切り日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='is_followed_weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='フォローしている人の倍率'),
            preserve_default=False,
        ),
    ]
